//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 原始程式碼已由 Microsoft.VSDesigner 自動產生，版本 4.0.30319.42000。
// 
#pragma warning disable 1591

namespace SDK_Log_Capture_Tool.pty.sfis.n1 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SFISTSPWebServiceSoap", Namespace="http://www.pegatroncorp.com/SFISWebService/")]
    public partial class SFISTSPWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetDatabaseInformationOperationCompleted;
        
        private System.Threading.SendOrPostCallback WTSP_LOGINOUTOperationCompleted;
        
        private System.Threading.SendOrPostCallback WTSP_LOGINOUT_PROGIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback WTSP_CHKROUTEOperationCompleted;
        
        private System.Threading.SendOrPostCallback WTSP_CHKROUTE_AOILOCOperationCompleted;
        
        private System.Threading.SendOrPostCallback WTSP_GETVERSIONOperationCompleted;
        
        private System.Threading.SendOrPostCallback WTSP_RESULTOperationCompleted;
        
        private System.Threading.SendOrPostCallback WTSP_RESULT_MASSDATAOperationCompleted;
        
        private System.Threading.SendOrPostCallback WTSP_GETIMACOperationCompleted;
        
        private System.Threading.SendOrPostCallback WTSP_GETIMAC_TOperationCompleted;
        
        private System.Threading.SendOrPostCallback WTSP_REPAIROperationCompleted;
        
        private System.Threading.SendOrPostCallback WTSP_REPAIR_LOCOperationCompleted;
        
        private System.Threading.SendOrPostCallback WTSP_DEVIF_MOOperationCompleted;
        
        private System.Threading.SendOrPostCallback WTSP_GETI1394OperationCompleted;
        
        private System.Threading.SendOrPostCallback WTSP_GETLABELOperationCompleted;
        
        private System.Threading.SendOrPostCallback WTSP_LOADKEYOperationCompleted;
        
        private System.Threading.SendOrPostCallback WTSP_SSD_INPUTDATAOperationCompleted;
        
        private System.Threading.SendOrPostCallback WTSP_INPUTGSDATAOperationCompleted;
        
        private System.Threading.SendOrPostCallback WTSP_ONLINE_REWORK_NOperationCompleted;
        
        private System.Threading.SendOrPostCallback WTSP_SEND_MAILOperationCompleted;
        
        private System.Threading.SendOrPostCallback WTSP_ASSIGN_DEVICEOperationCompleted;
        
        private System.Threading.SendOrPostCallback WTSP_LOADINFOOperationCompleted;
        
        private System.Threading.SendOrPostCallback WTSP_TSP_GET_INPUTDATAOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SFISTSPWebService() {
            this.Url = global::SDK_Log_Capture_Tool.Properties.Settings.Default.SDK_Log_Capture_Tool_pty_sfis_n1_SFISTSPWebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetDatabaseInformationCompletedEventHandler GetDatabaseInformationCompleted;
        
        /// <remarks/>
        public event WTSP_LOGINOUTCompletedEventHandler WTSP_LOGINOUTCompleted;
        
        /// <remarks/>
        public event WTSP_LOGINOUT_PROGIDCompletedEventHandler WTSP_LOGINOUT_PROGIDCompleted;
        
        /// <remarks/>
        public event WTSP_CHKROUTECompletedEventHandler WTSP_CHKROUTECompleted;
        
        /// <remarks/>
        public event WTSP_CHKROUTE_AOILOCCompletedEventHandler WTSP_CHKROUTE_AOILOCCompleted;
        
        /// <remarks/>
        public event WTSP_GETVERSIONCompletedEventHandler WTSP_GETVERSIONCompleted;
        
        /// <remarks/>
        public event WTSP_RESULTCompletedEventHandler WTSP_RESULTCompleted;
        
        /// <remarks/>
        public event WTSP_RESULT_MASSDATACompletedEventHandler WTSP_RESULT_MASSDATACompleted;
        
        /// <remarks/>
        public event WTSP_GETIMACCompletedEventHandler WTSP_GETIMACCompleted;
        
        /// <remarks/>
        public event WTSP_GETIMAC_TCompletedEventHandler WTSP_GETIMAC_TCompleted;
        
        /// <remarks/>
        public event WTSP_REPAIRCompletedEventHandler WTSP_REPAIRCompleted;
        
        /// <remarks/>
        public event WTSP_REPAIR_LOCCompletedEventHandler WTSP_REPAIR_LOCCompleted;
        
        /// <remarks/>
        public event WTSP_DEVIF_MOCompletedEventHandler WTSP_DEVIF_MOCompleted;
        
        /// <remarks/>
        public event WTSP_GETI1394CompletedEventHandler WTSP_GETI1394Completed;
        
        /// <remarks/>
        public event WTSP_GETLABELCompletedEventHandler WTSP_GETLABELCompleted;
        
        /// <remarks/>
        public event WTSP_LOADKEYCompletedEventHandler WTSP_LOADKEYCompleted;
        
        /// <remarks/>
        public event WTSP_SSD_INPUTDATACompletedEventHandler WTSP_SSD_INPUTDATACompleted;
        
        /// <remarks/>
        public event WTSP_INPUTGSDATACompletedEventHandler WTSP_INPUTGSDATACompleted;
        
        /// <remarks/>
        public event WTSP_ONLINE_REWORK_NCompletedEventHandler WTSP_ONLINE_REWORK_NCompleted;
        
        /// <remarks/>
        public event WTSP_SEND_MAILCompletedEventHandler WTSP_SEND_MAILCompleted;
        
        /// <remarks/>
        public event WTSP_ASSIGN_DEVICECompletedEventHandler WTSP_ASSIGN_DEVICECompleted;
        
        /// <remarks/>
        public event WTSP_LOADINFOCompletedEventHandler WTSP_LOADINFOCompleted;
        
        /// <remarks/>
        public event WTSP_TSP_GET_INPUTDATACompletedEventHandler WTSP_TSP_GET_INPUTDATACompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.pegatroncorp.com/SFISWebService/GetDatabaseInformation", RequestNamespace="http://www.pegatroncorp.com/SFISWebService/", ResponseNamespace="http://www.pegatroncorp.com/SFISWebService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetDatabaseInformation() {
            object[] results = this.Invoke("GetDatabaseInformation", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetDatabaseInformationAsync() {
            this.GetDatabaseInformationAsync(null);
        }
        
        /// <remarks/>
        public void GetDatabaseInformationAsync(object userState) {
            if ((this.GetDatabaseInformationOperationCompleted == null)) {
                this.GetDatabaseInformationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDatabaseInformationOperationCompleted);
            }
            this.InvokeAsync("GetDatabaseInformation", new object[0], this.GetDatabaseInformationOperationCompleted, userState);
        }
        
        private void OnGetDatabaseInformationOperationCompleted(object arg) {
            if ((this.GetDatabaseInformationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDatabaseInformationCompleted(this, new GetDatabaseInformationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.pegatroncorp.com/SFISWebService/WTSP_LOGINOUT", RequestNamespace="http://www.pegatroncorp.com/SFISWebService/", ResponseNamespace="http://www.pegatroncorp.com/SFISWebService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string WTSP_LOGINOUT(string programId, string programPassword, string op, string password, string device, string TSP, int status) {
            object[] results = this.Invoke("WTSP_LOGINOUT", new object[] {
                        programId,
                        programPassword,
                        op,
                        password,
                        device,
                        TSP,
                        status});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void WTSP_LOGINOUTAsync(string programId, string programPassword, string op, string password, string device, string TSP, int status) {
            this.WTSP_LOGINOUTAsync(programId, programPassword, op, password, device, TSP, status, null);
        }
        
        /// <remarks/>
        public void WTSP_LOGINOUTAsync(string programId, string programPassword, string op, string password, string device, string TSP, int status, object userState) {
            if ((this.WTSP_LOGINOUTOperationCompleted == null)) {
                this.WTSP_LOGINOUTOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWTSP_LOGINOUTOperationCompleted);
            }
            this.InvokeAsync("WTSP_LOGINOUT", new object[] {
                        programId,
                        programPassword,
                        op,
                        password,
                        device,
                        TSP,
                        status}, this.WTSP_LOGINOUTOperationCompleted, userState);
        }
        
        private void OnWTSP_LOGINOUTOperationCompleted(object arg) {
            if ((this.WTSP_LOGINOUTCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WTSP_LOGINOUTCompleted(this, new WTSP_LOGINOUTCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.pegatroncorp.com/SFISWebService/WTSP_LOGINOUT_PROGID", RequestNamespace="http://www.pegatroncorp.com/SFISWebService/", ResponseNamespace="http://www.pegatroncorp.com/SFISWebService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string WTSP_LOGINOUT_PROGID(string programId, string programPassword, string op, string password, string device, string TSP, int status, string PROGID, string SRC, string VER) {
            object[] results = this.Invoke("WTSP_LOGINOUT_PROGID", new object[] {
                        programId,
                        programPassword,
                        op,
                        password,
                        device,
                        TSP,
                        status,
                        PROGID,
                        SRC,
                        VER});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void WTSP_LOGINOUT_PROGIDAsync(string programId, string programPassword, string op, string password, string device, string TSP, int status, string PROGID, string SRC, string VER) {
            this.WTSP_LOGINOUT_PROGIDAsync(programId, programPassword, op, password, device, TSP, status, PROGID, SRC, VER, null);
        }
        
        /// <remarks/>
        public void WTSP_LOGINOUT_PROGIDAsync(string programId, string programPassword, string op, string password, string device, string TSP, int status, string PROGID, string SRC, string VER, object userState) {
            if ((this.WTSP_LOGINOUT_PROGIDOperationCompleted == null)) {
                this.WTSP_LOGINOUT_PROGIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWTSP_LOGINOUT_PROGIDOperationCompleted);
            }
            this.InvokeAsync("WTSP_LOGINOUT_PROGID", new object[] {
                        programId,
                        programPassword,
                        op,
                        password,
                        device,
                        TSP,
                        status,
                        PROGID,
                        SRC,
                        VER}, this.WTSP_LOGINOUT_PROGIDOperationCompleted, userState);
        }
        
        private void OnWTSP_LOGINOUT_PROGIDOperationCompleted(object arg) {
            if ((this.WTSP_LOGINOUT_PROGIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WTSP_LOGINOUT_PROGIDCompleted(this, new WTSP_LOGINOUT_PROGIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.pegatroncorp.com/SFISWebService/WTSP_CHKROUTE", RequestNamespace="http://www.pegatroncorp.com/SFISWebService/", ResponseNamespace="http://www.pegatroncorp.com/SFISWebService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string WTSP_CHKROUTE(string programId, string programPassword, string ISN, string device, string checkFlag, string checkData, int type) {
            object[] results = this.Invoke("WTSP_CHKROUTE", new object[] {
                        programId,
                        programPassword,
                        ISN,
                        device,
                        checkFlag,
                        checkData,
                        type});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void WTSP_CHKROUTEAsync(string programId, string programPassword, string ISN, string device, string checkFlag, string checkData, int type) {
            this.WTSP_CHKROUTEAsync(programId, programPassword, ISN, device, checkFlag, checkData, type, null);
        }
        
        /// <remarks/>
        public void WTSP_CHKROUTEAsync(string programId, string programPassword, string ISN, string device, string checkFlag, string checkData, int type, object userState) {
            if ((this.WTSP_CHKROUTEOperationCompleted == null)) {
                this.WTSP_CHKROUTEOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWTSP_CHKROUTEOperationCompleted);
            }
            this.InvokeAsync("WTSP_CHKROUTE", new object[] {
                        programId,
                        programPassword,
                        ISN,
                        device,
                        checkFlag,
                        checkData,
                        type}, this.WTSP_CHKROUTEOperationCompleted, userState);
        }
        
        private void OnWTSP_CHKROUTEOperationCompleted(object arg) {
            if ((this.WTSP_CHKROUTECompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WTSP_CHKROUTECompleted(this, new WTSP_CHKROUTECompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.pegatroncorp.com/SFISWebService/WTSP_CHKROUTE_AOILOC", RequestNamespace="http://www.pegatroncorp.com/SFISWebService/", ResponseNamespace="http://www.pegatroncorp.com/SFISWebService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string WTSP_CHKROUTE_AOILOC(string programId, string programPassword, string ISN, string device, string checkFlag, string checkData, int type, string aoiloc) {
            object[] results = this.Invoke("WTSP_CHKROUTE_AOILOC", new object[] {
                        programId,
                        programPassword,
                        ISN,
                        device,
                        checkFlag,
                        checkData,
                        type,
                        aoiloc});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void WTSP_CHKROUTE_AOILOCAsync(string programId, string programPassword, string ISN, string device, string checkFlag, string checkData, int type, string aoiloc) {
            this.WTSP_CHKROUTE_AOILOCAsync(programId, programPassword, ISN, device, checkFlag, checkData, type, aoiloc, null);
        }
        
        /// <remarks/>
        public void WTSP_CHKROUTE_AOILOCAsync(string programId, string programPassword, string ISN, string device, string checkFlag, string checkData, int type, string aoiloc, object userState) {
            if ((this.WTSP_CHKROUTE_AOILOCOperationCompleted == null)) {
                this.WTSP_CHKROUTE_AOILOCOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWTSP_CHKROUTE_AOILOCOperationCompleted);
            }
            this.InvokeAsync("WTSP_CHKROUTE_AOILOC", new object[] {
                        programId,
                        programPassword,
                        ISN,
                        device,
                        checkFlag,
                        checkData,
                        type,
                        aoiloc}, this.WTSP_CHKROUTE_AOILOCOperationCompleted, userState);
        }
        
        private void OnWTSP_CHKROUTE_AOILOCOperationCompleted(object arg) {
            if ((this.WTSP_CHKROUTE_AOILOCCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WTSP_CHKROUTE_AOILOCCompleted(this, new WTSP_CHKROUTE_AOILOCCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.pegatroncorp.com/SFISWebService/WTSP_GETVERSION", RequestNamespace="http://www.pegatroncorp.com/SFISWebService/", ResponseNamespace="http://www.pegatroncorp.com/SFISWebService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string WTSP_GETVERSION(string programId, string programPassword, string ISN, string device, string type, string ChkData, string ChkData2) {
            object[] results = this.Invoke("WTSP_GETVERSION", new object[] {
                        programId,
                        programPassword,
                        ISN,
                        device,
                        type,
                        ChkData,
                        ChkData2});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void WTSP_GETVERSIONAsync(string programId, string programPassword, string ISN, string device, string type, string ChkData, string ChkData2) {
            this.WTSP_GETVERSIONAsync(programId, programPassword, ISN, device, type, ChkData, ChkData2, null);
        }
        
        /// <remarks/>
        public void WTSP_GETVERSIONAsync(string programId, string programPassword, string ISN, string device, string type, string ChkData, string ChkData2, object userState) {
            if ((this.WTSP_GETVERSIONOperationCompleted == null)) {
                this.WTSP_GETVERSIONOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWTSP_GETVERSIONOperationCompleted);
            }
            this.InvokeAsync("WTSP_GETVERSION", new object[] {
                        programId,
                        programPassword,
                        ISN,
                        device,
                        type,
                        ChkData,
                        ChkData2}, this.WTSP_GETVERSIONOperationCompleted, userState);
        }
        
        private void OnWTSP_GETVERSIONOperationCompleted(object arg) {
            if ((this.WTSP_GETVERSIONCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WTSP_GETVERSIONCompleted(this, new WTSP_GETVERSIONCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.pegatroncorp.com/SFISWebService/WTSP_RESULT", RequestNamespace="http://www.pegatroncorp.com/SFISWebService/", ResponseNamespace="http://www.pegatroncorp.com/SFISWebService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string WTSP_RESULT(string programId, string programPassword, string ISN, string error, string device, string TSP, string data, int status, string CPKFlag) {
            object[] results = this.Invoke("WTSP_RESULT", new object[] {
                        programId,
                        programPassword,
                        ISN,
                        error,
                        device,
                        TSP,
                        data,
                        status,
                        CPKFlag});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void WTSP_RESULTAsync(string programId, string programPassword, string ISN, string error, string device, string TSP, string data, int status, string CPKFlag) {
            this.WTSP_RESULTAsync(programId, programPassword, ISN, error, device, TSP, data, status, CPKFlag, null);
        }
        
        /// <remarks/>
        public void WTSP_RESULTAsync(string programId, string programPassword, string ISN, string error, string device, string TSP, string data, int status, string CPKFlag, object userState) {
            if ((this.WTSP_RESULTOperationCompleted == null)) {
                this.WTSP_RESULTOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWTSP_RESULTOperationCompleted);
            }
            this.InvokeAsync("WTSP_RESULT", new object[] {
                        programId,
                        programPassword,
                        ISN,
                        error,
                        device,
                        TSP,
                        data,
                        status,
                        CPKFlag}, this.WTSP_RESULTOperationCompleted, userState);
        }
        
        private void OnWTSP_RESULTOperationCompleted(object arg) {
            if ((this.WTSP_RESULTCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WTSP_RESULTCompleted(this, new WTSP_RESULTCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.pegatroncorp.com/SFISWebService/WTSP_RESULT_MASSDATA", RequestNamespace="http://www.pegatroncorp.com/SFISWebService/", ResponseNamespace="http://www.pegatroncorp.com/SFISWebService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string WTSP_RESULT_MASSDATA(
                    string programId, 
                    string programPassword, 
                    string ISN, 
                    string error, 
                    string device, 
                    string TSP, 
                    string data, 
                    int status, 
                    string CPKFlag, 
                    string aoiloc, 
                    string data2, 
                    string data3, 
                    string data4, 
                    string data5, 
                    string data6, 
                    string data7, 
                    string data8) {
            object[] results = this.Invoke("WTSP_RESULT_MASSDATA", new object[] {
                        programId,
                        programPassword,
                        ISN,
                        error,
                        device,
                        TSP,
                        data,
                        status,
                        CPKFlag,
                        aoiloc,
                        data2,
                        data3,
                        data4,
                        data5,
                        data6,
                        data7,
                        data8});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void WTSP_RESULT_MASSDATAAsync(
                    string programId, 
                    string programPassword, 
                    string ISN, 
                    string error, 
                    string device, 
                    string TSP, 
                    string data, 
                    int status, 
                    string CPKFlag, 
                    string aoiloc, 
                    string data2, 
                    string data3, 
                    string data4, 
                    string data5, 
                    string data6, 
                    string data7, 
                    string data8) {
            this.WTSP_RESULT_MASSDATAAsync(programId, programPassword, ISN, error, device, TSP, data, status, CPKFlag, aoiloc, data2, data3, data4, data5, data6, data7, data8, null);
        }
        
        /// <remarks/>
        public void WTSP_RESULT_MASSDATAAsync(
                    string programId, 
                    string programPassword, 
                    string ISN, 
                    string error, 
                    string device, 
                    string TSP, 
                    string data, 
                    int status, 
                    string CPKFlag, 
                    string aoiloc, 
                    string data2, 
                    string data3, 
                    string data4, 
                    string data5, 
                    string data6, 
                    string data7, 
                    string data8, 
                    object userState) {
            if ((this.WTSP_RESULT_MASSDATAOperationCompleted == null)) {
                this.WTSP_RESULT_MASSDATAOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWTSP_RESULT_MASSDATAOperationCompleted);
            }
            this.InvokeAsync("WTSP_RESULT_MASSDATA", new object[] {
                        programId,
                        programPassword,
                        ISN,
                        error,
                        device,
                        TSP,
                        data,
                        status,
                        CPKFlag,
                        aoiloc,
                        data2,
                        data3,
                        data4,
                        data5,
                        data6,
                        data7,
                        data8}, this.WTSP_RESULT_MASSDATAOperationCompleted, userState);
        }
        
        private void OnWTSP_RESULT_MASSDATAOperationCompleted(object arg) {
            if ((this.WTSP_RESULT_MASSDATACompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WTSP_RESULT_MASSDATACompleted(this, new WTSP_RESULT_MASSDATACompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.pegatroncorp.com/SFISWebService/WTSP_GETIMAC", RequestNamespace="http://www.pegatroncorp.com/SFISWebService/", ResponseNamespace="http://www.pegatroncorp.com/SFISWebService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string WTSP_GETIMAC(string programId, string programPassword, string device, string ISN, int status, int imacnum) {
            object[] results = this.Invoke("WTSP_GETIMAC", new object[] {
                        programId,
                        programPassword,
                        device,
                        ISN,
                        status,
                        imacnum});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void WTSP_GETIMACAsync(string programId, string programPassword, string device, string ISN, int status, int imacnum) {
            this.WTSP_GETIMACAsync(programId, programPassword, device, ISN, status, imacnum, null);
        }
        
        /// <remarks/>
        public void WTSP_GETIMACAsync(string programId, string programPassword, string device, string ISN, int status, int imacnum, object userState) {
            if ((this.WTSP_GETIMACOperationCompleted == null)) {
                this.WTSP_GETIMACOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWTSP_GETIMACOperationCompleted);
            }
            this.InvokeAsync("WTSP_GETIMAC", new object[] {
                        programId,
                        programPassword,
                        device,
                        ISN,
                        status,
                        imacnum}, this.WTSP_GETIMACOperationCompleted, userState);
        }
        
        private void OnWTSP_GETIMACOperationCompleted(object arg) {
            if ((this.WTSP_GETIMACCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WTSP_GETIMACCompleted(this, new WTSP_GETIMACCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.pegatroncorp.com/SFISWebService/WTSP_GETIMAC_T", RequestNamespace="http://www.pegatroncorp.com/SFISWebService/", ResponseNamespace="http://www.pegatroncorp.com/SFISWebService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string WTSP_GETIMAC_T(string programId, string programPassword, string device, string ISN, int status, int imacnum, int type) {
            object[] results = this.Invoke("WTSP_GETIMAC_T", new object[] {
                        programId,
                        programPassword,
                        device,
                        ISN,
                        status,
                        imacnum,
                        type});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void WTSP_GETIMAC_TAsync(string programId, string programPassword, string device, string ISN, int status, int imacnum, int type) {
            this.WTSP_GETIMAC_TAsync(programId, programPassword, device, ISN, status, imacnum, type, null);
        }
        
        /// <remarks/>
        public void WTSP_GETIMAC_TAsync(string programId, string programPassword, string device, string ISN, int status, int imacnum, int type, object userState) {
            if ((this.WTSP_GETIMAC_TOperationCompleted == null)) {
                this.WTSP_GETIMAC_TOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWTSP_GETIMAC_TOperationCompleted);
            }
            this.InvokeAsync("WTSP_GETIMAC_T", new object[] {
                        programId,
                        programPassword,
                        device,
                        ISN,
                        status,
                        imacnum,
                        type}, this.WTSP_GETIMAC_TOperationCompleted, userState);
        }
        
        private void OnWTSP_GETIMAC_TOperationCompleted(object arg) {
            if ((this.WTSP_GETIMAC_TCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WTSP_GETIMAC_TCompleted(this, new WTSP_GETIMAC_TCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.pegatroncorp.com/SFISWebService/WTSP_REPAIR", RequestNamespace="http://www.pegatroncorp.com/SFISWebService/", ResponseNamespace="http://www.pegatroncorp.com/SFISWebService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string WTSP_REPAIR(string programId, string programPassword, string TYPE, string ISN, string DEV, string REASON, string DUTY, string NGRP, string TSP) {
            object[] results = this.Invoke("WTSP_REPAIR", new object[] {
                        programId,
                        programPassword,
                        TYPE,
                        ISN,
                        DEV,
                        REASON,
                        DUTY,
                        NGRP,
                        TSP});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void WTSP_REPAIRAsync(string programId, string programPassword, string TYPE, string ISN, string DEV, string REASON, string DUTY, string NGRP, string TSP) {
            this.WTSP_REPAIRAsync(programId, programPassword, TYPE, ISN, DEV, REASON, DUTY, NGRP, TSP, null);
        }
        
        /// <remarks/>
        public void WTSP_REPAIRAsync(string programId, string programPassword, string TYPE, string ISN, string DEV, string REASON, string DUTY, string NGRP, string TSP, object userState) {
            if ((this.WTSP_REPAIROperationCompleted == null)) {
                this.WTSP_REPAIROperationCompleted = new System.Threading.SendOrPostCallback(this.OnWTSP_REPAIROperationCompleted);
            }
            this.InvokeAsync("WTSP_REPAIR", new object[] {
                        programId,
                        programPassword,
                        TYPE,
                        ISN,
                        DEV,
                        REASON,
                        DUTY,
                        NGRP,
                        TSP}, this.WTSP_REPAIROperationCompleted, userState);
        }
        
        private void OnWTSP_REPAIROperationCompleted(object arg) {
            if ((this.WTSP_REPAIRCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WTSP_REPAIRCompleted(this, new WTSP_REPAIRCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.pegatroncorp.com/SFISWebService/WTSP_REPAIR_LOC", RequestNamespace="http://www.pegatroncorp.com/SFISWebService/", ResponseNamespace="http://www.pegatroncorp.com/SFISWebService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string WTSP_REPAIR_LOC(string programId, string programPassword, string TYPE, string ISN, string DEV, string REASON, string DUTY, string NGRP, string TSP, string LOC) {
            object[] results = this.Invoke("WTSP_REPAIR_LOC", new object[] {
                        programId,
                        programPassword,
                        TYPE,
                        ISN,
                        DEV,
                        REASON,
                        DUTY,
                        NGRP,
                        TSP,
                        LOC});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void WTSP_REPAIR_LOCAsync(string programId, string programPassword, string TYPE, string ISN, string DEV, string REASON, string DUTY, string NGRP, string TSP, string LOC) {
            this.WTSP_REPAIR_LOCAsync(programId, programPassword, TYPE, ISN, DEV, REASON, DUTY, NGRP, TSP, LOC, null);
        }
        
        /// <remarks/>
        public void WTSP_REPAIR_LOCAsync(string programId, string programPassword, string TYPE, string ISN, string DEV, string REASON, string DUTY, string NGRP, string TSP, string LOC, object userState) {
            if ((this.WTSP_REPAIR_LOCOperationCompleted == null)) {
                this.WTSP_REPAIR_LOCOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWTSP_REPAIR_LOCOperationCompleted);
            }
            this.InvokeAsync("WTSP_REPAIR_LOC", new object[] {
                        programId,
                        programPassword,
                        TYPE,
                        ISN,
                        DEV,
                        REASON,
                        DUTY,
                        NGRP,
                        TSP,
                        LOC}, this.WTSP_REPAIR_LOCOperationCompleted, userState);
        }
        
        private void OnWTSP_REPAIR_LOCOperationCompleted(object arg) {
            if ((this.WTSP_REPAIR_LOCCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WTSP_REPAIR_LOCCompleted(this, new WTSP_REPAIR_LOCCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.pegatroncorp.com/SFISWebService/WTSP_DEVIF_MO", RequestNamespace="http://www.pegatroncorp.com/SFISWebService/", ResponseNamespace="http://www.pegatroncorp.com/SFISWebService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string WTSP_DEVIF_MO(string programId, string programPassword, string device, string MO) {
            object[] results = this.Invoke("WTSP_DEVIF_MO", new object[] {
                        programId,
                        programPassword,
                        device,
                        MO});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void WTSP_DEVIF_MOAsync(string programId, string programPassword, string device, string MO) {
            this.WTSP_DEVIF_MOAsync(programId, programPassword, device, MO, null);
        }
        
        /// <remarks/>
        public void WTSP_DEVIF_MOAsync(string programId, string programPassword, string device, string MO, object userState) {
            if ((this.WTSP_DEVIF_MOOperationCompleted == null)) {
                this.WTSP_DEVIF_MOOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWTSP_DEVIF_MOOperationCompleted);
            }
            this.InvokeAsync("WTSP_DEVIF_MO", new object[] {
                        programId,
                        programPassword,
                        device,
                        MO}, this.WTSP_DEVIF_MOOperationCompleted, userState);
        }
        
        private void OnWTSP_DEVIF_MOOperationCompleted(object arg) {
            if ((this.WTSP_DEVIF_MOCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WTSP_DEVIF_MOCompleted(this, new WTSP_DEVIF_MOCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.pegatroncorp.com/SFISWebService/WTSP_GETI1394", RequestNamespace="http://www.pegatroncorp.com/SFISWebService/", ResponseNamespace="http://www.pegatroncorp.com/SFISWebService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string WTSP_GETI1394(string programId, string programPassword, string ISN, string device, int status, int I1394NUM) {
            object[] results = this.Invoke("WTSP_GETI1394", new object[] {
                        programId,
                        programPassword,
                        ISN,
                        device,
                        status,
                        I1394NUM});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void WTSP_GETI1394Async(string programId, string programPassword, string ISN, string device, int status, int I1394NUM) {
            this.WTSP_GETI1394Async(programId, programPassword, ISN, device, status, I1394NUM, null);
        }
        
        /// <remarks/>
        public void WTSP_GETI1394Async(string programId, string programPassword, string ISN, string device, int status, int I1394NUM, object userState) {
            if ((this.WTSP_GETI1394OperationCompleted == null)) {
                this.WTSP_GETI1394OperationCompleted = new System.Threading.SendOrPostCallback(this.OnWTSP_GETI1394OperationCompleted);
            }
            this.InvokeAsync("WTSP_GETI1394", new object[] {
                        programId,
                        programPassword,
                        ISN,
                        device,
                        status,
                        I1394NUM}, this.WTSP_GETI1394OperationCompleted, userState);
        }
        
        private void OnWTSP_GETI1394OperationCompleted(object arg) {
            if ((this.WTSP_GETI1394Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WTSP_GETI1394Completed(this, new WTSP_GETI1394CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.pegatroncorp.com/SFISWebService/WTSP_GETLABEL", RequestNamespace="http://www.pegatroncorp.com/SFISWebService/", ResponseNamespace="http://www.pegatroncorp.com/SFISWebService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string WTSP_GETLABEL(string programId, string programPassword, string type, string ISN, string DEV, string status) {
            object[] results = this.Invoke("WTSP_GETLABEL", new object[] {
                        programId,
                        programPassword,
                        type,
                        ISN,
                        DEV,
                        status});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void WTSP_GETLABELAsync(string programId, string programPassword, string type, string ISN, string DEV, string status) {
            this.WTSP_GETLABELAsync(programId, programPassword, type, ISN, DEV, status, null);
        }
        
        /// <remarks/>
        public void WTSP_GETLABELAsync(string programId, string programPassword, string type, string ISN, string DEV, string status, object userState) {
            if ((this.WTSP_GETLABELOperationCompleted == null)) {
                this.WTSP_GETLABELOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWTSP_GETLABELOperationCompleted);
            }
            this.InvokeAsync("WTSP_GETLABEL", new object[] {
                        programId,
                        programPassword,
                        type,
                        ISN,
                        DEV,
                        status}, this.WTSP_GETLABELOperationCompleted, userState);
        }
        
        private void OnWTSP_GETLABELOperationCompleted(object arg) {
            if ((this.WTSP_GETLABELCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WTSP_GETLABELCompleted(this, new WTSP_GETLABELCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.pegatroncorp.com/SFISWebService/WTSP_LOADKEY", RequestNamespace="http://www.pegatroncorp.com/SFISWebService/", ResponseNamespace="http://www.pegatroncorp.com/SFISWebService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string WTSP_LOADKEY(string programId, string programPassword, string SNTYPE, string DATA, string OP) {
            object[] results = this.Invoke("WTSP_LOADKEY", new object[] {
                        programId,
                        programPassword,
                        SNTYPE,
                        DATA,
                        OP});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void WTSP_LOADKEYAsync(string programId, string programPassword, string SNTYPE, string DATA, string OP) {
            this.WTSP_LOADKEYAsync(programId, programPassword, SNTYPE, DATA, OP, null);
        }
        
        /// <remarks/>
        public void WTSP_LOADKEYAsync(string programId, string programPassword, string SNTYPE, string DATA, string OP, object userState) {
            if ((this.WTSP_LOADKEYOperationCompleted == null)) {
                this.WTSP_LOADKEYOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWTSP_LOADKEYOperationCompleted);
            }
            this.InvokeAsync("WTSP_LOADKEY", new object[] {
                        programId,
                        programPassword,
                        SNTYPE,
                        DATA,
                        OP}, this.WTSP_LOADKEYOperationCompleted, userState);
        }
        
        private void OnWTSP_LOADKEYOperationCompleted(object arg) {
            if ((this.WTSP_LOADKEYCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WTSP_LOADKEYCompleted(this, new WTSP_LOADKEYCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.pegatroncorp.com/SFISWebService/WTSP_SSD_INPUTDATA", RequestNamespace="http://www.pegatroncorp.com/SFISWebService/", ResponseNamespace="http://www.pegatroncorp.com/SFISWebService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string WTSP_SSD_INPUTDATA(string programId, string programPassword, string device, string data, string type) {
            object[] results = this.Invoke("WTSP_SSD_INPUTDATA", new object[] {
                        programId,
                        programPassword,
                        device,
                        data,
                        type});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void WTSP_SSD_INPUTDATAAsync(string programId, string programPassword, string device, string data, string type) {
            this.WTSP_SSD_INPUTDATAAsync(programId, programPassword, device, data, type, null);
        }
        
        /// <remarks/>
        public void WTSP_SSD_INPUTDATAAsync(string programId, string programPassword, string device, string data, string type, object userState) {
            if ((this.WTSP_SSD_INPUTDATAOperationCompleted == null)) {
                this.WTSP_SSD_INPUTDATAOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWTSP_SSD_INPUTDATAOperationCompleted);
            }
            this.InvokeAsync("WTSP_SSD_INPUTDATA", new object[] {
                        programId,
                        programPassword,
                        device,
                        data,
                        type}, this.WTSP_SSD_INPUTDATAOperationCompleted, userState);
        }
        
        private void OnWTSP_SSD_INPUTDATAOperationCompleted(object arg) {
            if ((this.WTSP_SSD_INPUTDATACompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WTSP_SSD_INPUTDATACompleted(this, new WTSP_SSD_INPUTDATACompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.pegatroncorp.com/SFISWebService/WTSP_INPUTGSDATA", RequestNamespace="http://www.pegatroncorp.com/SFISWebService/", ResponseNamespace="http://www.pegatroncorp.com/SFISWebService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string WTSP_INPUTGSDATA(string programId, string programPassword, string ISN, string data) {
            object[] results = this.Invoke("WTSP_INPUTGSDATA", new object[] {
                        programId,
                        programPassword,
                        ISN,
                        data});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void WTSP_INPUTGSDATAAsync(string programId, string programPassword, string ISN, string data) {
            this.WTSP_INPUTGSDATAAsync(programId, programPassword, ISN, data, null);
        }
        
        /// <remarks/>
        public void WTSP_INPUTGSDATAAsync(string programId, string programPassword, string ISN, string data, object userState) {
            if ((this.WTSP_INPUTGSDATAOperationCompleted == null)) {
                this.WTSP_INPUTGSDATAOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWTSP_INPUTGSDATAOperationCompleted);
            }
            this.InvokeAsync("WTSP_INPUTGSDATA", new object[] {
                        programId,
                        programPassword,
                        ISN,
                        data}, this.WTSP_INPUTGSDATAOperationCompleted, userState);
        }
        
        private void OnWTSP_INPUTGSDATAOperationCompleted(object arg) {
            if ((this.WTSP_INPUTGSDATACompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WTSP_INPUTGSDATACompleted(this, new WTSP_INPUTGSDATACompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.pegatroncorp.com/SFISWebService/WTSP_ONLINE_REWORK_N", RequestNamespace="http://www.pegatroncorp.com/SFISWebService/", ResponseNamespace="http://www.pegatroncorp.com/SFISWebService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string WTSP_ONLINE_REWORK_N(string programId, string programPassword, string type, string data1, string data2, string data3, string flag) {
            object[] results = this.Invoke("WTSP_ONLINE_REWORK_N", new object[] {
                        programId,
                        programPassword,
                        type,
                        data1,
                        data2,
                        data3,
                        flag});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void WTSP_ONLINE_REWORK_NAsync(string programId, string programPassword, string type, string data1, string data2, string data3, string flag) {
            this.WTSP_ONLINE_REWORK_NAsync(programId, programPassword, type, data1, data2, data3, flag, null);
        }
        
        /// <remarks/>
        public void WTSP_ONLINE_REWORK_NAsync(string programId, string programPassword, string type, string data1, string data2, string data3, string flag, object userState) {
            if ((this.WTSP_ONLINE_REWORK_NOperationCompleted == null)) {
                this.WTSP_ONLINE_REWORK_NOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWTSP_ONLINE_REWORK_NOperationCompleted);
            }
            this.InvokeAsync("WTSP_ONLINE_REWORK_N", new object[] {
                        programId,
                        programPassword,
                        type,
                        data1,
                        data2,
                        data3,
                        flag}, this.WTSP_ONLINE_REWORK_NOperationCompleted, userState);
        }
        
        private void OnWTSP_ONLINE_REWORK_NOperationCompleted(object arg) {
            if ((this.WTSP_ONLINE_REWORK_NCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WTSP_ONLINE_REWORK_NCompleted(this, new WTSP_ONLINE_REWORK_NCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.pegatroncorp.com/SFISWebService/WTSP_SEND_MAIL", RequestNamespace="http://www.pegatroncorp.com/SFISWebService/", ResponseNamespace="http://www.pegatroncorp.com/SFISWebService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string WTSP_SEND_MAIL(string programId, string programPassword, string subject, string sendto, string sendtext) {
            object[] results = this.Invoke("WTSP_SEND_MAIL", new object[] {
                        programId,
                        programPassword,
                        subject,
                        sendto,
                        sendtext});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void WTSP_SEND_MAILAsync(string programId, string programPassword, string subject, string sendto, string sendtext) {
            this.WTSP_SEND_MAILAsync(programId, programPassword, subject, sendto, sendtext, null);
        }
        
        /// <remarks/>
        public void WTSP_SEND_MAILAsync(string programId, string programPassword, string subject, string sendto, string sendtext, object userState) {
            if ((this.WTSP_SEND_MAILOperationCompleted == null)) {
                this.WTSP_SEND_MAILOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWTSP_SEND_MAILOperationCompleted);
            }
            this.InvokeAsync("WTSP_SEND_MAIL", new object[] {
                        programId,
                        programPassword,
                        subject,
                        sendto,
                        sendtext}, this.WTSP_SEND_MAILOperationCompleted, userState);
        }
        
        private void OnWTSP_SEND_MAILOperationCompleted(object arg) {
            if ((this.WTSP_SEND_MAILCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WTSP_SEND_MAILCompleted(this, new WTSP_SEND_MAILCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.pegatroncorp.com/SFISWebService/WTSP_ASSIGN_DEVICE", RequestNamespace="http://www.pegatroncorp.com/SFISWebService/", ResponseNamespace="http://www.pegatroncorp.com/SFISWebService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string WTSP_ASSIGN_DEVICE(string programId, string programPassword, string type, string DEVType, string DEVID, string ACTType, string ISN, string flag, string data1, string data2) {
            object[] results = this.Invoke("WTSP_ASSIGN_DEVICE", new object[] {
                        programId,
                        programPassword,
                        type,
                        DEVType,
                        DEVID,
                        ACTType,
                        ISN,
                        flag,
                        data1,
                        data2});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void WTSP_ASSIGN_DEVICEAsync(string programId, string programPassword, string type, string DEVType, string DEVID, string ACTType, string ISN, string flag, string data1, string data2) {
            this.WTSP_ASSIGN_DEVICEAsync(programId, programPassword, type, DEVType, DEVID, ACTType, ISN, flag, data1, data2, null);
        }
        
        /// <remarks/>
        public void WTSP_ASSIGN_DEVICEAsync(string programId, string programPassword, string type, string DEVType, string DEVID, string ACTType, string ISN, string flag, string data1, string data2, object userState) {
            if ((this.WTSP_ASSIGN_DEVICEOperationCompleted == null)) {
                this.WTSP_ASSIGN_DEVICEOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWTSP_ASSIGN_DEVICEOperationCompleted);
            }
            this.InvokeAsync("WTSP_ASSIGN_DEVICE", new object[] {
                        programId,
                        programPassword,
                        type,
                        DEVType,
                        DEVID,
                        ACTType,
                        ISN,
                        flag,
                        data1,
                        data2}, this.WTSP_ASSIGN_DEVICEOperationCompleted, userState);
        }
        
        private void OnWTSP_ASSIGN_DEVICEOperationCompleted(object arg) {
            if ((this.WTSP_ASSIGN_DEVICECompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WTSP_ASSIGN_DEVICECompleted(this, new WTSP_ASSIGN_DEVICECompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.pegatroncorp.com/SFISWebService/WTSP_LOADINFO", RequestNamespace="http://www.pegatroncorp.com/SFISWebService/", ResponseNamespace="http://www.pegatroncorp.com/SFISWebService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string WTSP_LOADINFO(string programId, string programPassword, string pType, string pFlag, string pKey1, string pKey2, string pLndata1, string pLndata2, string pLndata3, string pLndata4, string pActtype, string pUserid) {
            object[] results = this.Invoke("WTSP_LOADINFO", new object[] {
                        programId,
                        programPassword,
                        pType,
                        pFlag,
                        pKey1,
                        pKey2,
                        pLndata1,
                        pLndata2,
                        pLndata3,
                        pLndata4,
                        pActtype,
                        pUserid});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void WTSP_LOADINFOAsync(string programId, string programPassword, string pType, string pFlag, string pKey1, string pKey2, string pLndata1, string pLndata2, string pLndata3, string pLndata4, string pActtype, string pUserid) {
            this.WTSP_LOADINFOAsync(programId, programPassword, pType, pFlag, pKey1, pKey2, pLndata1, pLndata2, pLndata3, pLndata4, pActtype, pUserid, null);
        }
        
        /// <remarks/>
        public void WTSP_LOADINFOAsync(string programId, string programPassword, string pType, string pFlag, string pKey1, string pKey2, string pLndata1, string pLndata2, string pLndata3, string pLndata4, string pActtype, string pUserid, object userState) {
            if ((this.WTSP_LOADINFOOperationCompleted == null)) {
                this.WTSP_LOADINFOOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWTSP_LOADINFOOperationCompleted);
            }
            this.InvokeAsync("WTSP_LOADINFO", new object[] {
                        programId,
                        programPassword,
                        pType,
                        pFlag,
                        pKey1,
                        pKey2,
                        pLndata1,
                        pLndata2,
                        pLndata3,
                        pLndata4,
                        pActtype,
                        pUserid}, this.WTSP_LOADINFOOperationCompleted, userState);
        }
        
        private void OnWTSP_LOADINFOOperationCompleted(object arg) {
            if ((this.WTSP_LOADINFOCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WTSP_LOADINFOCompleted(this, new WTSP_LOADINFOCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.pegatroncorp.com/SFISWebService/WTSP_TSP_GET_INPUTDATA", RequestNamespace="http://www.pegatroncorp.com/SFISWebService/", ResponseNamespace="http://www.pegatroncorp.com/SFISWebService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string WTSP_TSP_GET_INPUTDATA(string programId, string programPassword, string pFlag, string pType, string pData, int pDev, string pChkData1, string pChkData2) {
            object[] results = this.Invoke("WTSP_TSP_GET_INPUTDATA", new object[] {
                        programId,
                        programPassword,
                        pFlag,
                        pType,
                        pData,
                        pDev,
                        pChkData1,
                        pChkData2});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void WTSP_TSP_GET_INPUTDATAAsync(string programId, string programPassword, string pFlag, string pType, string pData, int pDev, string pChkData1, string pChkData2) {
            this.WTSP_TSP_GET_INPUTDATAAsync(programId, programPassword, pFlag, pType, pData, pDev, pChkData1, pChkData2, null);
        }
        
        /// <remarks/>
        public void WTSP_TSP_GET_INPUTDATAAsync(string programId, string programPassword, string pFlag, string pType, string pData, int pDev, string pChkData1, string pChkData2, object userState) {
            if ((this.WTSP_TSP_GET_INPUTDATAOperationCompleted == null)) {
                this.WTSP_TSP_GET_INPUTDATAOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWTSP_TSP_GET_INPUTDATAOperationCompleted);
            }
            this.InvokeAsync("WTSP_TSP_GET_INPUTDATA", new object[] {
                        programId,
                        programPassword,
                        pFlag,
                        pType,
                        pData,
                        pDev,
                        pChkData1,
                        pChkData2}, this.WTSP_TSP_GET_INPUTDATAOperationCompleted, userState);
        }
        
        private void OnWTSP_TSP_GET_INPUTDATAOperationCompleted(object arg) {
            if ((this.WTSP_TSP_GET_INPUTDATACompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WTSP_TSP_GET_INPUTDATACompleted(this, new WTSP_TSP_GET_INPUTDATACompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void GetDatabaseInformationCompletedEventHandler(object sender, GetDatabaseInformationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDatabaseInformationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDatabaseInformationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void WTSP_LOGINOUTCompletedEventHandler(object sender, WTSP_LOGINOUTCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WTSP_LOGINOUTCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WTSP_LOGINOUTCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void WTSP_LOGINOUT_PROGIDCompletedEventHandler(object sender, WTSP_LOGINOUT_PROGIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WTSP_LOGINOUT_PROGIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WTSP_LOGINOUT_PROGIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void WTSP_CHKROUTECompletedEventHandler(object sender, WTSP_CHKROUTECompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WTSP_CHKROUTECompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WTSP_CHKROUTECompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void WTSP_CHKROUTE_AOILOCCompletedEventHandler(object sender, WTSP_CHKROUTE_AOILOCCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WTSP_CHKROUTE_AOILOCCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WTSP_CHKROUTE_AOILOCCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void WTSP_GETVERSIONCompletedEventHandler(object sender, WTSP_GETVERSIONCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WTSP_GETVERSIONCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WTSP_GETVERSIONCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void WTSP_RESULTCompletedEventHandler(object sender, WTSP_RESULTCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WTSP_RESULTCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WTSP_RESULTCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void WTSP_RESULT_MASSDATACompletedEventHandler(object sender, WTSP_RESULT_MASSDATACompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WTSP_RESULT_MASSDATACompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WTSP_RESULT_MASSDATACompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void WTSP_GETIMACCompletedEventHandler(object sender, WTSP_GETIMACCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WTSP_GETIMACCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WTSP_GETIMACCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void WTSP_GETIMAC_TCompletedEventHandler(object sender, WTSP_GETIMAC_TCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WTSP_GETIMAC_TCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WTSP_GETIMAC_TCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void WTSP_REPAIRCompletedEventHandler(object sender, WTSP_REPAIRCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WTSP_REPAIRCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WTSP_REPAIRCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void WTSP_REPAIR_LOCCompletedEventHandler(object sender, WTSP_REPAIR_LOCCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WTSP_REPAIR_LOCCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WTSP_REPAIR_LOCCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void WTSP_DEVIF_MOCompletedEventHandler(object sender, WTSP_DEVIF_MOCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WTSP_DEVIF_MOCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WTSP_DEVIF_MOCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void WTSP_GETI1394CompletedEventHandler(object sender, WTSP_GETI1394CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WTSP_GETI1394CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WTSP_GETI1394CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void WTSP_GETLABELCompletedEventHandler(object sender, WTSP_GETLABELCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WTSP_GETLABELCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WTSP_GETLABELCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void WTSP_LOADKEYCompletedEventHandler(object sender, WTSP_LOADKEYCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WTSP_LOADKEYCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WTSP_LOADKEYCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void WTSP_SSD_INPUTDATACompletedEventHandler(object sender, WTSP_SSD_INPUTDATACompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WTSP_SSD_INPUTDATACompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WTSP_SSD_INPUTDATACompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void WTSP_INPUTGSDATACompletedEventHandler(object sender, WTSP_INPUTGSDATACompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WTSP_INPUTGSDATACompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WTSP_INPUTGSDATACompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void WTSP_ONLINE_REWORK_NCompletedEventHandler(object sender, WTSP_ONLINE_REWORK_NCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WTSP_ONLINE_REWORK_NCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WTSP_ONLINE_REWORK_NCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void WTSP_SEND_MAILCompletedEventHandler(object sender, WTSP_SEND_MAILCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WTSP_SEND_MAILCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WTSP_SEND_MAILCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void WTSP_ASSIGN_DEVICECompletedEventHandler(object sender, WTSP_ASSIGN_DEVICECompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WTSP_ASSIGN_DEVICECompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WTSP_ASSIGN_DEVICECompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void WTSP_LOADINFOCompletedEventHandler(object sender, WTSP_LOADINFOCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WTSP_LOADINFOCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WTSP_LOADINFOCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void WTSP_TSP_GET_INPUTDATACompletedEventHandler(object sender, WTSP_TSP_GET_INPUTDATACompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WTSP_TSP_GET_INPUTDATACompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WTSP_TSP_GET_INPUTDATACompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591