//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 原始程式碼已由 Microsoft.VSDesigner 自動產生，版本 4.0.30319.42000。
// 
#pragma warning disable 1591

namespace SDK_Log_Capture_Tool.com.borland.demo {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Service1Soap", Namespace="http://tempuri.org/")]
    public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback A_ReadMeFirstOperationCompleted;
        
        private System.Threading.SendOrPostCallback echoStringOperationCompleted;
        
        private System.Threading.SendOrPostCallback echoFloatOperationCompleted;
        
        private System.Threading.SendOrPostCallback echoStringArrayOperationCompleted;
        
        private System.Threading.SendOrPostCallback echoObjectArrayOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetNowAsShortStringOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetNowAsDateOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRandomNumberOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetUserInformationOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUserInformationOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUserObjectOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetUserObjectOperationCompleted;
        
        private System.Threading.SendOrPostCallback IncreaseUserAgeOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service1() {
            this.Url = global::SDK_Log_Capture_Tool.Properties.Settings.Default.SDK_Log_Capture_Tool_com_borland_demo_Service1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event A_ReadMeFirstCompletedEventHandler A_ReadMeFirstCompleted;
        
        /// <remarks/>
        public event echoStringCompletedEventHandler echoStringCompleted;
        
        /// <remarks/>
        public event echoFloatCompletedEventHandler echoFloatCompleted;
        
        /// <remarks/>
        public event echoStringArrayCompletedEventHandler echoStringArrayCompleted;
        
        /// <remarks/>
        public event echoObjectArrayCompletedEventHandler echoObjectArrayCompleted;
        
        /// <remarks/>
        public event GetNowAsShortStringCompletedEventHandler GetNowAsShortStringCompleted;
        
        /// <remarks/>
        public event GetNowAsDateCompletedEventHandler GetNowAsDateCompleted;
        
        /// <remarks/>
        public event GetRandomNumberCompletedEventHandler GetRandomNumberCompleted;
        
        /// <remarks/>
        public event SetUserInformationCompletedEventHandler SetUserInformationCompleted;
        
        /// <remarks/>
        public event GetUserInformationCompletedEventHandler GetUserInformationCompleted;
        
        /// <remarks/>
        public event GetUserObjectCompletedEventHandler GetUserObjectCompleted;
        
        /// <remarks/>
        public event SetUserObjectCompletedEventHandler SetUserObjectCompleted;
        
        /// <remarks/>
        public event IncreaseUserAgeCompletedEventHandler IncreaseUserAgeCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/A_ReadMeFirst", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] A_ReadMeFirst() {
            object[] results = this.Invoke("A_ReadMeFirst", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void A_ReadMeFirstAsync() {
            this.A_ReadMeFirstAsync(null);
        }
        
        /// <remarks/>
        public void A_ReadMeFirstAsync(object userState) {
            if ((this.A_ReadMeFirstOperationCompleted == null)) {
                this.A_ReadMeFirstOperationCompleted = new System.Threading.SendOrPostCallback(this.OnA_ReadMeFirstOperationCompleted);
            }
            this.InvokeAsync("A_ReadMeFirst", new object[0], this.A_ReadMeFirstOperationCompleted, userState);
        }
        
        private void OnA_ReadMeFirstOperationCompleted(object arg) {
            if ((this.A_ReadMeFirstCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.A_ReadMeFirstCompleted(this, new A_ReadMeFirstCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/echoString", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string echoString(string sString) {
            object[] results = this.Invoke("echoString", new object[] {
                        sString});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void echoStringAsync(string sString) {
            this.echoStringAsync(sString, null);
        }
        
        /// <remarks/>
        public void echoStringAsync(string sString, object userState) {
            if ((this.echoStringOperationCompleted == null)) {
                this.echoStringOperationCompleted = new System.Threading.SendOrPostCallback(this.OnechoStringOperationCompleted);
            }
            this.InvokeAsync("echoString", new object[] {
                        sString}, this.echoStringOperationCompleted, userState);
        }
        
        private void OnechoStringOperationCompleted(object arg) {
            if ((this.echoStringCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.echoStringCompleted(this, new echoStringCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/echoFloat", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public float echoFloat(float fFloat) {
            object[] results = this.Invoke("echoFloat", new object[] {
                        fFloat});
            return ((float)(results[0]));
        }
        
        /// <remarks/>
        public void echoFloatAsync(float fFloat) {
            this.echoFloatAsync(fFloat, null);
        }
        
        /// <remarks/>
        public void echoFloatAsync(float fFloat, object userState) {
            if ((this.echoFloatOperationCompleted == null)) {
                this.echoFloatOperationCompleted = new System.Threading.SendOrPostCallback(this.OnechoFloatOperationCompleted);
            }
            this.InvokeAsync("echoFloat", new object[] {
                        fFloat}, this.echoFloatOperationCompleted, userState);
        }
        
        private void OnechoFloatOperationCompleted(object arg) {
            if ((this.echoFloatCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.echoFloatCompleted(this, new echoFloatCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/echoStringArray", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] echoStringArray(string[] aStringArray) {
            object[] results = this.Invoke("echoStringArray", new object[] {
                        aStringArray});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void echoStringArrayAsync(string[] aStringArray) {
            this.echoStringArrayAsync(aStringArray, null);
        }
        
        /// <remarks/>
        public void echoStringArrayAsync(string[] aStringArray, object userState) {
            if ((this.echoStringArrayOperationCompleted == null)) {
                this.echoStringArrayOperationCompleted = new System.Threading.SendOrPostCallback(this.OnechoStringArrayOperationCompleted);
            }
            this.InvokeAsync("echoStringArray", new object[] {
                        aStringArray}, this.echoStringArrayOperationCompleted, userState);
        }
        
        private void OnechoStringArrayOperationCompleted(object arg) {
            if ((this.echoStringArrayCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.echoStringArrayCompleted(this, new echoStringArrayCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/echoObjectArray", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public User[] echoObjectArray(User[] aObjectArray) {
            object[] results = this.Invoke("echoObjectArray", new object[] {
                        aObjectArray});
            return ((User[])(results[0]));
        }
        
        /// <remarks/>
        public void echoObjectArrayAsync(User[] aObjectArray) {
            this.echoObjectArrayAsync(aObjectArray, null);
        }
        
        /// <remarks/>
        public void echoObjectArrayAsync(User[] aObjectArray, object userState) {
            if ((this.echoObjectArrayOperationCompleted == null)) {
                this.echoObjectArrayOperationCompleted = new System.Threading.SendOrPostCallback(this.OnechoObjectArrayOperationCompleted);
            }
            this.InvokeAsync("echoObjectArray", new object[] {
                        aObjectArray}, this.echoObjectArrayOperationCompleted, userState);
        }
        
        private void OnechoObjectArrayOperationCompleted(object arg) {
            if ((this.echoObjectArrayCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.echoObjectArrayCompleted(this, new echoObjectArrayCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetNowAsShortString", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetNowAsShortString() {
            object[] results = this.Invoke("GetNowAsShortString", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetNowAsShortStringAsync() {
            this.GetNowAsShortStringAsync(null);
        }
        
        /// <remarks/>
        public void GetNowAsShortStringAsync(object userState) {
            if ((this.GetNowAsShortStringOperationCompleted == null)) {
                this.GetNowAsShortStringOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetNowAsShortStringOperationCompleted);
            }
            this.InvokeAsync("GetNowAsShortString", new object[0], this.GetNowAsShortStringOperationCompleted, userState);
        }
        
        private void OnGetNowAsShortStringOperationCompleted(object arg) {
            if ((this.GetNowAsShortStringCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetNowAsShortStringCompleted(this, new GetNowAsShortStringCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetNowAsDate", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.DateTime GetNowAsDate() {
            object[] results = this.Invoke("GetNowAsDate", new object[0]);
            return ((System.DateTime)(results[0]));
        }
        
        /// <remarks/>
        public void GetNowAsDateAsync() {
            this.GetNowAsDateAsync(null);
        }
        
        /// <remarks/>
        public void GetNowAsDateAsync(object userState) {
            if ((this.GetNowAsDateOperationCompleted == null)) {
                this.GetNowAsDateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetNowAsDateOperationCompleted);
            }
            this.InvokeAsync("GetNowAsDate", new object[0], this.GetNowAsDateOperationCompleted, userState);
        }
        
        private void OnGetNowAsDateOperationCompleted(object arg) {
            if ((this.GetNowAsDateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetNowAsDateCompleted(this, new GetNowAsDateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetRandomNumber", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int GetRandomNumber(int nMin, int nMax) {
            object[] results = this.Invoke("GetRandomNumber", new object[] {
                        nMin,
                        nMax});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void GetRandomNumberAsync(int nMin, int nMax) {
            this.GetRandomNumberAsync(nMin, nMax, null);
        }
        
        /// <remarks/>
        public void GetRandomNumberAsync(int nMin, int nMax, object userState) {
            if ((this.GetRandomNumberOperationCompleted == null)) {
                this.GetRandomNumberOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRandomNumberOperationCompleted);
            }
            this.InvokeAsync("GetRandomNumber", new object[] {
                        nMin,
                        nMax}, this.GetRandomNumberOperationCompleted, userState);
        }
        
        private void OnGetRandomNumberOperationCompleted(object arg) {
            if ((this.GetRandomNumberCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRandomNumberCompleted(this, new GetRandomNumberCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SetUserInformation", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool SetUserInformation(string sFirstName, string sLastName, int nAge, string sStreet, string sCity) {
            object[] results = this.Invoke("SetUserInformation", new object[] {
                        sFirstName,
                        sLastName,
                        nAge,
                        sStreet,
                        sCity});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void SetUserInformationAsync(string sFirstName, string sLastName, int nAge, string sStreet, string sCity) {
            this.SetUserInformationAsync(sFirstName, sLastName, nAge, sStreet, sCity, null);
        }
        
        /// <remarks/>
        public void SetUserInformationAsync(string sFirstName, string sLastName, int nAge, string sStreet, string sCity, object userState) {
            if ((this.SetUserInformationOperationCompleted == null)) {
                this.SetUserInformationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetUserInformationOperationCompleted);
            }
            this.InvokeAsync("SetUserInformation", new object[] {
                        sFirstName,
                        sLastName,
                        nAge,
                        sStreet,
                        sCity}, this.SetUserInformationOperationCompleted, userState);
        }
        
        private void OnSetUserInformationOperationCompleted(object arg) {
            if ((this.SetUserInformationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetUserInformationCompleted(this, new SetUserInformationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUserInformation", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetUserInformation() {
            object[] results = this.Invoke("GetUserInformation", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetUserInformationAsync() {
            this.GetUserInformationAsync(null);
        }
        
        /// <remarks/>
        public void GetUserInformationAsync(object userState) {
            if ((this.GetUserInformationOperationCompleted == null)) {
                this.GetUserInformationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserInformationOperationCompleted);
            }
            this.InvokeAsync("GetUserInformation", new object[0], this.GetUserInformationOperationCompleted, userState);
        }
        
        private void OnGetUserInformationOperationCompleted(object arg) {
            if ((this.GetUserInformationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserInformationCompleted(this, new GetUserInformationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUserObject", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public User GetUserObject() {
            object[] results = this.Invoke("GetUserObject", new object[0]);
            return ((User)(results[0]));
        }
        
        /// <remarks/>
        public void GetUserObjectAsync() {
            this.GetUserObjectAsync(null);
        }
        
        /// <remarks/>
        public void GetUserObjectAsync(object userState) {
            if ((this.GetUserObjectOperationCompleted == null)) {
                this.GetUserObjectOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserObjectOperationCompleted);
            }
            this.InvokeAsync("GetUserObject", new object[0], this.GetUserObjectOperationCompleted, userState);
        }
        
        private void OnGetUserObjectOperationCompleted(object arg) {
            if ((this.GetUserObjectCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserObjectCompleted(this, new GetUserObjectCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SetUserObject", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool SetUserObject(User usr) {
            object[] results = this.Invoke("SetUserObject", new object[] {
                        usr});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void SetUserObjectAsync(User usr) {
            this.SetUserObjectAsync(usr, null);
        }
        
        /// <remarks/>
        public void SetUserObjectAsync(User usr, object userState) {
            if ((this.SetUserObjectOperationCompleted == null)) {
                this.SetUserObjectOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetUserObjectOperationCompleted);
            }
            this.InvokeAsync("SetUserObject", new object[] {
                        usr}, this.SetUserObjectOperationCompleted, userState);
        }
        
        private void OnSetUserObjectOperationCompleted(object arg) {
            if ((this.SetUserObjectCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetUserObjectCompleted(this, new SetUserObjectCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IncreaseUserAge", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public User IncreaseUserAge(User usr, int nIncrease) {
            object[] results = this.Invoke("IncreaseUserAge", new object[] {
                        usr,
                        nIncrease});
            return ((User)(results[0]));
        }
        
        /// <remarks/>
        public void IncreaseUserAgeAsync(User usr, int nIncrease) {
            this.IncreaseUserAgeAsync(usr, nIncrease, null);
        }
        
        /// <remarks/>
        public void IncreaseUserAgeAsync(User usr, int nIncrease, object userState) {
            if ((this.IncreaseUserAgeOperationCompleted == null)) {
                this.IncreaseUserAgeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIncreaseUserAgeOperationCompleted);
            }
            this.InvokeAsync("IncreaseUserAge", new object[] {
                        usr,
                        nIncrease}, this.IncreaseUserAgeOperationCompleted, userState);
        }
        
        private void OnIncreaseUserAgeOperationCompleted(object arg) {
            if ((this.IncreaseUserAgeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IncreaseUserAgeCompleted(this, new IncreaseUserAgeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class User {
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string streetField;
        
        private string cityField;
        
        private int ageField;
        
        /// <remarks/>
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        public string Street {
            get {
                return this.streetField;
            }
            set {
                this.streetField = value;
            }
        }
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public int Age {
            get {
                return this.ageField;
            }
            set {
                this.ageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void A_ReadMeFirstCompletedEventHandler(object sender, A_ReadMeFirstCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class A_ReadMeFirstCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal A_ReadMeFirstCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void echoStringCompletedEventHandler(object sender, echoStringCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class echoStringCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal echoStringCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void echoFloatCompletedEventHandler(object sender, echoFloatCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class echoFloatCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal echoFloatCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public float Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((float)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void echoStringArrayCompletedEventHandler(object sender, echoStringArrayCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class echoStringArrayCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal echoStringArrayCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void echoObjectArrayCompletedEventHandler(object sender, echoObjectArrayCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class echoObjectArrayCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal echoObjectArrayCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public User[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((User[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetNowAsShortStringCompletedEventHandler(object sender, GetNowAsShortStringCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetNowAsShortStringCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetNowAsShortStringCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetNowAsDateCompletedEventHandler(object sender, GetNowAsDateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetNowAsDateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetNowAsDateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.DateTime Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.DateTime)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetRandomNumberCompletedEventHandler(object sender, GetRandomNumberCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRandomNumberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRandomNumberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void SetUserInformationCompletedEventHandler(object sender, SetUserInformationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetUserInformationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SetUserInformationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetUserInformationCompletedEventHandler(object sender, GetUserInformationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserInformationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUserInformationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetUserObjectCompletedEventHandler(object sender, GetUserObjectCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserObjectCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUserObjectCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public User Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((User)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void SetUserObjectCompletedEventHandler(object sender, SetUserObjectCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetUserObjectCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SetUserObjectCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void IncreaseUserAgeCompletedEventHandler(object sender, IncreaseUserAgeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IncreaseUserAgeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IncreaseUserAgeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public User Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((User)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591